name: CI/CD Deployment Pipeline

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: Code Quality Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Run linting
      run: npm run lint
      
    - name: Run tests
      run: npm test
      
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-output
        path: .

  qa-deploy:
    name: Deploy to QA
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
    environment: qa
    
    steps:
    - name: Download test results
      uses: actions/download-artifact@v4
      with:
        name: test-output
        path: .
    - name: Deploy to QA
      run: |
        echo "Deploying to QA environment..."
        echo "Build successful: ${{ needs.ci.result }}"

  production-deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment: production
    
    steps:
    - name: Download test results
      uses: actions/download-artifact@v4
      with:
        name: test-output
        path: . 
    - name: Production deployment
      run: |
        echo "🚀 DEPLOYING TO PRODUCTION"
        echo "All Tests Passed Successfully"
        
  slack-notify:
    name: Slack Notification
    runs-on: ubuntu-latest
    needs: production-deploy
    if: success()
    steps:
    - name: Send Slack Notification
      uses: slackapi/slack-github-action@v1
      with:
        payload: |
          {
             "text": "*CI/CD Deployment Pipeline - Production Deployment Successful!* ✅\n*Repository:* ${{ github.repository }}\n*Branch:* ${{ github.ref_name }}\n*Commit:* ${{ github.sha }}\n*By:* ${{ github.actor }}\n*View Run:* ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
